import Head from 'next/head';

export default function Blog() {
  return (
    <div>
      <Head>
        <title>ThemeLad | Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Blog</h1>
    </div>
  );
}
